version: '2'

networks:
  dotnet_network:
    driver: bridge

services:
  mssqldb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssqlserver15
    restart: always
    hostname: mssqldb
    environment:
      SA_PASSWORD: Password123456789
      ACCEPT_EULA: Y
    networks:
      - dotnet_network
    ports:
      - 9594:1433
    volumes:
      - pgdata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dotnet_api-build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_api-build
    working_dir: /app
    volumes:
      - ./dotnet-api:/app
    command: >
      sh -c "git clone https://github.com/BTS-SIO-STB/ApiDotnet-DevFullStack.git &&\ 
              cd ApiDotnet-DevFullStack &&\
              dotnet restore DeezerDevFullStack.API/DeezerDevFullStack.API.csproj && \
              dotnet publish DeezerDevFullStack.API/DeezerDevFullStack.API.csproj -c Release -o /app/publish /p:UseAppHost=false"

  dotnet_api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0-alpine
    container_name: dotnet_api
    working_dir: /app
    volumes:
      - ./dotnet-api:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    depends_on:
      - mssqldb
      - dotnet_api-build
    networks:
      - dotnet_network
    command: ["dotnet", "/app/publish/DeezerDevFullStack.API.dll"]

volumes:
  pgdata:
